client/src/App/App.jsx
client/src/api/index.js
client/src/components/Auth/ForgotPassword/index.jsx
client/src/components/Auth/ForgotPassword/styles.js

Fixes Issue #14 
Added code enhancements

Added fixes for new Feature

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

Fixed #17 
Add CONTRIBTING.md and CODE_OF_CONDUCT.md file

Added CONTRIBTING.md and CODE_OF_CONDUCT.md file

---

README.md

added Contributors section and  in the README file and also in table of content

Add Contributors Pannel

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/other.md

Added Templates to:
1. Report a Bug.
2. Request a Feature.
3. Other
This Pull Request Solves #21

Update issue templates

---

server/.env.example
server/controllers/user.js

- **I Atharva Rekhawar have worked for #37**
**I accept the fact that i have followed the guidelines and have not copied the codes from around the internet**
- **My pull request closes <#37>**
**Here are the pictures of changes that I have made 🔽**
<attach screenshots here>
---

fix: Added fixes for #37

---

README.md
rules/ENV_VARIABLES.md

- **I Pritam Kundu have worked for #40**
**I accept the fact that i have followed the guidelines and have not copied the codes from around the internet**
- **My pull request closes #40**
**Here are the pictures of changes that i have made 🔽**
<attach screenshots here>
---

[FEATURE] Proper Doumentation for local setup

---

client/src/components/PostDetails/styles.js

- I [Sunil Kumar](https://github.com/0rigin-c0de) have worked for #59 
- My pull request closes #59 
Here are the pictures of the changes that I have made 🔽
I have change font size and make it bolder to look attractive and style to italic 
---

 style title

---

client/src/index.css

- I [Sunil Kumar](https://github.com/0rigin-c0de) have worked for #61 
- My pull request closes #61 
Here are the pictures of the changes that I have made 🔽
---

Customize scrollbar appearance

---

server/controllers/user.js
server/index.js
server/routes/users.js

- Added Comment tabs for users
- Now users can view their recent comments.

feat: added fully functional comments tab for users

---

client/src/actions/posts.js

- I [onionSequences](https://github.com/onionSequences) have worked for 66
I accept the fact that i have followed the guidelines and have not copied the codes from around the internet
- My pull request closes #66 
Here are the pictures of changes that i have made 🔽
---

fix(posts): sanitize chars in all occurrences

---

server/package-lock.json
server/package.json

- I [Ltwoz](https://github.com/Ltwoz) have worked for #68 
I accept the fact that i have followed the guidelines and have not copied the codes from around the internet
- My pull request closes #68 
Here are the pictures of changes that i have made 🔽
---

Change nodemon from server dependencies to dev dependencies

---

README.md

Hi,
- I [Devanshu Augusty](https://github.com/Devanshu-Augusty) have made some corrections to the spelling in the README.md file. Please review and merge this pull request at your earliest convenience
Before :
After:
---

Improvement link spelling corrected in README.md file

---

client/src/index.jsx

- I <Priyanka Ramachandran [My Github Profile](https://github.com/Priyankaa2503) have worked for #76 
- My pull request closes #76 
---

fixed console warning bug

---

client/src/components/Input/index.jsx
client/src/components/Input/styles.js

- I <krishna seth](https://github.com/a-s-t-e-y-a) have worked for #79
- My pull request closes #79
---

#79 bug Fixed :Outlines are not visible in dark mode are fixed

---

client/src/components/Form/Form.jsx
client/src/components/Search/Search.jsx

- I [Faisal Husain Shaikh](https://github.com/Faisalhs51) have worked for #97 
- My pull request closes #97 

Fixed tags input size

---

client/src/components/Paginate/Paginate.jsx
client/src/components/PostDetails/CommentSection/index.jsx
client/src/components/PostDetails/PostDetails.jsx
client/src/components/PostDetails/RecommendedPosts.jsx
client/src/components/User/Details/index.jsx
client/src/index.css

- I [David Padilla](https://github.com/cesardlinx) have worked for #89 
- My pull request closes #89 
---

fix: change SwipeableViews import in UserDetails index file (#89)

---

client/src/components/UserIcon/avatar.js

- I [abi beniyal](https://github.com/beneyalraj) have worked for #102 
- My pull request closes #102 
---

refactor: avoid square-bracket notation when accessing properties

---

client/src/components/User/Details/index.jsx
client/src/hooks.js

- I [David Padilla](https://github.com/cesardlinx) have worked for #100
- My pull request closes #100
---

fix: recover tab navigation functionality in user detail sections 

---

client/src/components/PostDetails/CommentSection/index.jsx
client/src/components/PostDetails/CommentSection/styles.js
client/src/components/PostDetails/PostDetails.jsx
client/src/components/PostDetails/styles.js
client/src/components/Search/Search.jsx

- I [Faisal Husain Shaikh](https://github.com/faisalhs51)> have worked for #107 
- My pull request closes #107 
<attach screenshots here>
---

feat: light mode colors enhancements

---

server/controllers/user.js

- I [Nicolas Evangelista](https://github.com/nikolai1312) have worked for #85 
- My pull request closes #85 
---

fix: fixing get user in user controller

---

README.md
client/src/components/Form/Form.jsx
client/src/components/User/Details/index.jsx
client/src/service-worker.js

- I [abi beniyal](https://github.com/beneyalraj) have worked for #116 
- My pull request closes #116 
---

fix: resolved variable shadowing and a unreachable line in the code

---

README.md

- I [AdiSuyash](https://github.com/adisuyash) have worked for #121 
I have replaced the Hacktoberfest banner & did some necessary documentation changes which will provide a better user experience.
This pull request introduces two main changes:
1. **Hacktoberfest Banner Replacement** : I have replaced the Old Banner of Hacktoberfest by a header LOGO.
2. **Chore** : I've re-written some words & also maintained alignment. 
- My pull request closes #121 
[AdiSuyash](github.com/adisuyash) have worked for #121

docs: hacktoberfest banner replacement

---

client/package-lock.json
client/package.json

Reverts warmachine028/memories#192

Revert "Bump react-router-dom from 6.26.1 to 6.26.2 in /client"

---

client/src/providers/Theme.jsx

- I [Jai Marothiya](https://github.com/Jai-Marothiya) have worked for #195
- My pull request closes #195 
<attach screenshots here>
---

refactor: rename local variables to fix shadows issue
